#!/usr/bin/env python3

import clang.cindex
from hashlib import sha256 as hashfunc
from os.path import relpath, dirname
import datetime
import yaml
import sys
import uuid
from .. utils.utils import print_stderr
from ..options import get_versions

def get_hash(source):
    f = open(source, 'r', encoding='utf-8')
    hsh = hashfunc()
    for l in f:
        hsh.update(l.encode('utf-8'))

    f.close()
    return hsh.hexdigest()

class YAMLWriter(object):
    def __init__(self, source, prps, is32bit, is_correctness_wit, saveto, path, shift = None):
        self._source = source
        self._relsource = relpath(source, dirname(saveto))
        self._prps = prps
        self._is32bit = is32bit
        self._correctness_wit = is_correctness_wit

        self.test = []
        self.errorLoc = None
        self.errorExpr = None
        self.calls = dict()
        self.witness = []
        self.shift = shift

        self.parse(path)


    def add_metadata(self):
        witness = {}
        witness['entry_type'] = "violation_sequence" if not self._correctness_wit else "invariant_set"
        witness['metadata'] = {
            'format_version' : "2.1",
            'creation_time' :  '{date:%Y-%m-%dT%T}Z'.format(date=datetime.datetime.utcnow()),
            'producer' : {'name' : 'witch',
                          'version' : get_versions()[0] },
            'uuid' : str(uuid.uuid4()),
            'task' :
                { 'input_files' : [self._relsource],
                  'input_file_hashes' : { self._relsource : get_hash(self._source)},
                  'specification' : ','.join(self._prps.ltl()),
                  'data_model' : "ILP32" if self._is32bit else "LP64",
                  'language' : "C"}
        }
        self.witness.append(witness)


    def generate_violation_witness(self, path):
        """
        Take a .test file generated by a tool and generate a new
        .yml file from it that has all the needed metadata.

        @param path         the .waypoints file
        """

        assert self.errorLoc or self._prps.termination(), "Failed generating a YAML witness"

        self.add_metadata()
        self.create_content()


    def generate_correctness_witness(self):
        self.add_metadata()

        # So far we can only create trivial correctness witnesses
        self.witness[0]['content'] = []

    def dump(self):
        print(self.witness)

    def write(self, to):
        with open(to, "w") as witness_file:
            yaml.safe_dump(self.witness, witness_file, default_style=None, sort_keys=False)



    # Traverse the AST, find the right brackets of functions and the full expression of the target
    def traverse_AST(self, node):

        # get infinitely recurring location
        if self._prps.termination() and self.errorLoc and not self.errorExpr:
            self.errorExpr = _get_recurring_location(node, self.errorLoc)

        for child in node.get_children():

            if not child.location.file or child.location.file.name != self._source:
                continue

            start = child.extent.start
            end = child.extent.end

            if child.kind == clang.cindex.CursorKind.CALL_EXPR and (start.line, start.column) in self.calls:
                self.calls[(start.line, start.column)] = end.line, end.column - 1

            if self.errorExpr or not self.errorLoc or not child.kind.is_expression():
                self.traverse_AST(child)
                continue

            # check range of the expression
            err_line = self.errorLoc[0]
            err_col = self.errorLoc[1]
            if not self.errorExpr and location_in_range(err_line, err_col, \
                                                        start.line, start.column, \
                                                        end.line, end.column):
                self.errorExpr = start.line, start.column
            self.traverse_AST(child)



    def create_content(self):
        sys.setrecursionlimit(2048)

        index = clang.cindex.Index.create()
        tu = index.parse(self._source, args=['-fbracket-depth=2048'])
        root = tu.cursor
        self.traverse_AST(root)

        if self.errorLoc and not self.errorExpr:
            print_stderr("Warning: Could not get target location for witness")
            self.errorExpr = self.errorLoc

        content = []

        for call in self.test:
            new_location = self.calls[(call[0], call[1])]
            assert new_location, "Failed creating witness"

            segment = []
            waypoint = { 'type' : 'function_return',
                          'action' : 'cycle' if call[3] else 'follow',
                          'constraint' : {
                            'format' : 'ext_c_expression',
                            'value' : '\\result == ' + call[2]
                          },
                          'location' : {
                            'file_name' : self._relsource,
                            'line' : new_location[0],
                            'column' : new_location[1]
                          }

                        }
            segment.append({'waypoint' : waypoint})
            content.append({'segment' : segment})

        if self.errorLoc:
            last_segment = []
            location = { 'file_name' : self._relsource,
                            'line' : self.errorExpr[0],
                            'column' : self.errorExpr[1]
                       }

            if self._prps.termination():
                last = { 'type'       : 'assumption',
                         'action'     : 'cycle',
                         'location'   : location,
                         'constraint' : {
                            'format' : 'c_expression',
                            'value'  : '1'
                          }
                       }
            else:
                last = { 'type'     : 'target',
                         'action'   : 'follow',
                         'location' : location
                       }


            last_segment.append({'waypoint' : last})
            content.append({'segment' : last_segment})

        self.witness[0]['content'] = content


    def parse(self, path):
        with open(path, "r") as testfile:
            cycle = False
            for line in testfile.readlines():
                if line[0] == '@':
                    self.errorLoc = tuple(map(int, line.strip('\n').split(':')[2:]))
                    break
                call = line.strip('\n').split(':')
                name = call[0]
                line = int(call[1])
                col = int(call[2])
                value = call[3]
                cycle = (len(call) == 5) # is there the cycle flag?
                self.test.append((line, col, value, cycle, name))
                self.calls[(line, col)] = None

        # No need for this if we have cycle waypoints
        if cycle:
            self.errorLoc = None

        if self.shift:
            self.shift_back()

    def shift_back(self):
        add_lines = 1 if self._source.endswith('.i') else 0
        tmp_test = self.test.copy()
        new_calls = {}
        for i in range(len(self.test)):
            call = self.test[i]
            og_line = call[0] - add_lines
            og_column = call[1]
            if og_line in self.shift.keys():
                for col in sorted(self.shift[og_line].keys()):
                    if og_column > col:
                        og_column -= self.shift[og_line][col]
                    else:
                        break
            tmp_test[i] = (og_line, og_column,
                           self.test[i][2],
                           self.test[i][3],
                           self.test[i][4])
            new_calls[(og_line, og_column)] = None
        self.test = tmp_test
        self.calls = new_calls

        # now the same for the error location
        og_line = self.errorLoc[0] - add_lines
        og_column = self.errorLoc[1]

        if og_line in self.shift.keys():
            if og_line in self.shift.keys():
                for col in sorted(self.shift[og_line].keys()):
                    if og_column > col:
                        og_column -= self.shift[og_line][col]

        self.errorLoc = og_line, og_column

    def generate_harness(self, output):

        return_types = [('bool', '_Bool'),
                        ('char', 'char'),
                        ('int', 'int'),
                        ('long', 'long'),
                        ('longlong', 'long long'),
                        ('short', 'short'),
                        ('size_t', 'size_t'),
                        ('uchar', 'unsigned char'),
                        ('uint', 'unsigned int'),
                        ('ulong', 'unsigned long'),
                        ('ulonglong', 'unsigned long long'),
                        ('ushort', 'unsigned short'),
                        ('unsigned', 'unsigned')]

        returns = { '__VERIFIER_nondet_{}'.format(t[0]) : (t[1], []) for t in return_types }

        for item in self.test:
            if item[4] in returns.keys():
                returns[item[4]][1].append(item[2])

        harness_lines = ['#include <stddef.h>']
        for function_name in returns.keys():
            return_type = returns[function_name][0]
            values = returns[function_name][1]

            harness_lines.append('{t} {name}(){{'.format(name=function_name, t=return_type))
            harness_lines.append('    static unsigned int index = 0;')
            harness_lines.append('    {t} retval = 0;'.format(t=return_type))
            if values:
                harness_lines.append('    switch (index) {')
                for i in range(len(values)):
                    harness_lines.append('    case {index}: retval = {value}; break;'
                                         .format(index=i, value=values[i]))
                harness_lines.append('    }')

            harness_lines.append('    ++index;')
            harness_lines.append('    return retval;')
            harness_lines.append('}')
            harness_lines.append('\n')

        with open(output, 'w') as harness_file:
            harness_file.writelines(s + '\n' for s in harness_lines)

def _get_recurring_location(node, error_loc):
    n_start = node.extent.start
    n_end = node.extent.end
    children = list(node.get_children())

    recurring_node = None

    if (node.kind == clang.cindex.CursorKind.FOR_STMT or \
        node.kind == clang.cindex.CursorKind.WHILE_STMT):

        if (error_loc[0] == n_start.line and error_loc[1] == n_start.column) or \
            location_in_range(error_loc[0], error_loc[1],
                              children[0].extent.start.line, children[0].extent.start.column,
                              children[-2].extent.end.line, children[-2].extent.end.column):
            return children[-1].extent.start.line, children[-1].extent.start.column

    if node.kind == clang.cindex.CursorKind.DO_STMT:

        if (error_loc[0] == children[0].extent.end.line and \
           error_loc[1] == children[0].extent.end.column - 1) or \
           location_in_range(error_loc[0], error_loc[1],
                            children[1].extent.start.line, children[1].extent.start.column,
                            children[1].extent.end.line, children[1].extent.end.column):
            return children[0].extent.start.line, children[0].extent.start.column

    if node.kind == clang.cindex.CursorKind.IF_STMT:

        if (error_loc[0] == children[0].extent.start.line and \
           error_loc[1] == children[0].extent.start.column) or \
           location_in_range(error_loc[0], error_loc[1],
                             children[0].extent.start.line, children[0].extent.start.column,
                             children[0].extent.end.line, children[0].extent.end.column):
            return n_start.line, n_start.column

    if node.kind == clang.cindex.CursorKind.SWITCH_STMT and \
       error_loc[0] == n_start.line and \
       error_loc[1] == n_start.column:
        return n_start.line, n_start.column

    if (node.kind.is_statement() or node.kind.is_declaration()) and \
        error_loc[0] == n_start.line and \
        error_loc[1] == n_start.column:
         return n_start.line, n_start.column

def location_in_range(line, col, startline, startcol, endline, endcol):

    if startline > line or endline < line:
        return False

    if startline == line and startcol > col:
        return False

    if endline == line and endcol < col:
        return False

    return True
