#!/bin/bash

pushd transforms/build-${LLVM_VERSION} || exit 1
SYMBIOTIC_VERSION=`git rev-parse HEAD`
SYMBIOTIC_BUILD_TYPE=$(grep 'CMAKE_BUILD_TYPE[:=]' CMakeCache.txt | sed 's@.*=\(.*\)@\1@')
popd

pushd dg/build-${LLVM_VERSION} || exit 1
DG_VERSION=`git rev-parse HEAD`
DG_BUILD_TYPE=$(grep 'CMAKE_BUILD_TYPE[:=]' CMakeCache.txt | sed 's@.*=\(.*\)@\1@')
popd

pushd sbt-slicer/build-${LLVM_VERSION} || exit 1
SBT_SLICER_VERSION=`git rev-parse HEAD`
SBT_SLICER_BUILD_TYPE=$(grep 'CMAKE_BUILD_TYPE[:=]' CMakeCache.txt | sed 's@.*=\(.*\)@\1@')
popd

pushd sbt-instrumentation/build-${LLVM_VERSION} || exit 1
INSTRUMENTATION_VERSION=`git rev-parse HEAD`
INSTRUMENTATION_BUILD_TYPE=$(grep 'CMAKE_BUILD_TYPE[:=]' CMakeCache.txt | sed 's@.*=\(.*\)@\1@')
popd

if [ "$BUILD_Z3" = "yes" ]; then
	pushd z3/build || exit 1
	Z3_VERSION=`git rev-parse HEAD`
	Z3_BUILD_TYPE=$(grep 'CMAKE_BUILD_TYPE[:=]' CMakeCache.txt | sed 's@.*=\(.*\)@\1@')
	popd
fi


pushd witch-klee/build-${LLVM_VERSION} || exit 1
WITCH_KLEE_VERSION=`git rev-parse HEAD`
WITCH_KLEE_BUILD_TYPE=$(grep 'CMAKE_BUILD_TYPE[:=]' CMakeCache.txt | sed 's@.*=\(.*\)@\1@')
popd

VERSFILE="$SRCDIR/lib/symbioticpy/symbiotic/versions.py"
echo "#!/usr/bin/env python3" > $VERSFILE
echo "# This file is automatically generated by symbiotic-build.sh" >> $VERSFILE
echo "" >> $VERSFILE
echo "versions = {" >> $VERSFILE
echo -e "\t'symbiotic' : '$SYMBIOTIC_VERSION'," >> $VERSFILE
echo -e "\t'dg' : '$DG_VERSION'," >> $VERSFILE
echo -e "\t'sbt-slicer' : '$SBT_SLICER_VERSION'," >> $VERSFILE
echo -e "\t'witch-klee' : '$WITCH_KLEE_VERSION'," >> $VERSFILE
echo -e "\t'sbt-instrumentation' : '$INSTRUMENTATION_VERSION'," >> $VERSFILE

if [ "$BUILD_Z3" = "yes" ]; then
	echo -e "\t'z3' : '$Z3_VERSION'," >> $VERSFILE
fi

echo -e "}\n" >> $VERSFILE

echo -e "llvm_version = '${LLVM_VERSION}'\n" >> $VERSFILE

echo "build_types = {" >> $VERSFILE
echo -e "\t'symbiotic' : '$SYMBIOTIC_BUILD_TYPE'," >> $VERSFILE
echo -e "\t'dg' : '$DG_BUILD_TYPE'," >> $VERSFILE
echo -e "\t'sbt-slicer' : '$SBT_SLICER_BUILD_TYPE'," >> $VERSFILE
echo -e "\t'witch-klee' : '$WITCH_KLEE_BUILD_TYPE'," >> $VERSFILE
echo -e "\t'sbt-instrumentation' : '$INSTRUMENTATION_BUILD_TYPE'," >> $VERSFILE

if [ "$BUILD_Z3" = "yes" ]; then
	echo -e "\t'z3' : '$Z3_BUILD_TYPE'," >> $VERSFILE
fi

echo -e "}\n" >> $VERSFILE

